import flet as ft
def main(page :ft.Page):
    page.horizontal_alignment=ft.CrossAxisAlignment.CENTER
    page.vertical_alignment=ft.MainAxisAlignment.CENTER
    page.bgcolor=ft.Colors.BLACK
    page.window_min_width = 500
    imagem=ft.Container(
        expand=2,
        border_radius=ft.border_radius.vertical(top=20),
        clip_behavior=ft.ClipBehavior.NONE,
        width=300,
        content=ft.Image(
            src='https://th.bing.com/th/id/R.3c56dabb0d2a53634d57b159d15108fd?rik=kzQ7yI95msWd4Q&riu=http%3a%2f%2fclashfanat.ru%2fwp-content%2fuploads%2f2016%2f12%2fVarvar.png&ehk=akBpJ5zXQ3MvzROLdEf3OMRK9hSGriCZdnXPKkSK2hE%3d&risl=&pid=ImgRaw&r=0',
            scale=ft.Scale(scale=1.3),
            offset=ft.Offset(x=0,y=-0.1)
            ),
        gradient=ft.LinearGradient(
            begin=ft.alignment.bottom_left,
            end=ft.alignment.bottom_right,
            colors=[ft.Colors.BROWN,ft.Colors.BLACK87]
        )
    )
    info=ft.Container(
        width=300,
        padding=ft.padding.all(20),
        expand=2,
        content=ft.Column(
            controls=[
                ft.Text(value='level 4',color=ft.Colors.ORANGE,size=20),
                ft.Text(
                    value='BÁRBARO',
                    weight=ft.FontWeight.BOLD,
                    color=ft.Colors.BLACK,
                    size=35,
                ),
                ft.Text(
                    value='descrição do personagem...',
                    text_align=ft.TextAlign.CENTER
                )
            ],
            horizontal_alignment=ft.CrossAxisAlignment.CENTER
        )
    )
    skills=ft.Container(
        expand=1,
        padding=ft.padding.symmetric(horizontal=20),
        bgcolor=ft.Colors.ORANGE,
        border_radius=ft.border_radius.vertical(bottom=20),
        content=ft.Row(
            controls=[
                ft.Column(
                    expand=1,
                    alignment=ft.MainAxisAlignment.CENTER,
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                    spacing=0,
                    controls=[
                        ft.Text(
                            value='20',
                            color=ft.Colors.WHITE,
                            weight=ft.FontWeight.BOLD,
                            size=30
                        ),
                        ft.Text(
                            value='defesa',
                            color=ft.Colors.WHITE
                        )
                    ]
                ),
                ft.Column(
                    expand=1,
                    alignment=ft.MainAxisAlignment.CENTER,
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                    spacing=0,
                    controls=[
                        ft.Text(
                            value='20',
                            color=ft.Colors.WHITE,
                            weight=ft.FontWeight.BOLD,
                            size=30
                        ),
                        ft.Text(
                            value='defesa',
                            color=ft.Colors.WHITE
                        )
                    ]
                ),
                ft.Column(
                    expand=1,
                    alignment=ft.MainAxisAlignment.CENTER,
                    horizontal_alignment=ft.CrossAxisAlignment.CENTER,
                    spacing=0,
                    controls=[
                        ft.Text(
                            value='20',
                            color=ft.Colors.WHITE,
                            weight=ft.FontWeight.BOLD,
                            size=30
                        ),
                        ft.Text(
                            value='defesa',
                            color=ft.Colors.WHITE
                        )
                    ]
                )
            ]
        )
        )
    layout=ft.Container(
        width=300,
        clip_behavior=ft.ClipBehavior.NONE,
        height=500,
        bgcolor=ft.Colors.WHITE,
        shadow=ft.BoxShadow(blur_radius=100,color=ft.Colors.BROWN),
        border_radius=ft.border_radius.all(20),
        content=ft.Column(
            spacing=0,
            controls=[
                imagem,
                info,
                skills,
            ]
        )
    )
    page.add(layout)
if __name__=="__main__":
    ft.app(target=main)